return {
    -- "hrsh7th/nvim-cmp",
    -- event = "InsertEnter",
    -- dependencies = {
    --     "hrsh7th/cmp-nvim-lsp",
    --     "hrsh7th/cmp-path",
    --     "hrsh7th/cmp-buffer",
    --     "hrsh7th/cmp-cmdline",
    --     "L3MON4D3/LuaSnip",
    --     "saadparwaiz1/cmp_luasnip",
    --     "rafamadriz/friendly-snippets",
    --     "onsails/lspkind-nvim",
    -- },
    -- config = function()
    --     local cmp = require("cmp")
    --     local lspkind = require("lspkind")
    --     cmp.setup({
    --         snippet = {
    --             expand = function(args)
    --                 require("luasnip").lsp_expand(args.body)
    --             end,
    --         },
    --         sources = cmp.config.sources({
    --             { name = "nvim_lsp" },
    --             { name = "luasnip" },
    --         }, {
    --             { name = "buffer" },
    --             { name = "path" },
    --         }),
    --         formatting = {
    --             format = lspkind.cmp_format({
    --                 with_text = true, -- do not show text alongside icons
    --                 maxwidth = 50, -- prevent the popup from showing more than provided characters (e.g 50 will not show more than 50 characters)
    --                 before = function(entry, vim_item)
    --                     -- Source 显示提示来源
    --                     vim_item.menu = "[" .. string.upper(entry.source.name) .. "]"
    --                     return vim_item
    --                 end,
    --             }),
    --         },
    --         mapping = cmp.mapping.preset.insert({
    --             ["<C-b>"] = cmp.mapping.scroll_docs(-4),
    --             ["<C-f>"] = cmp.mapping.scroll_docs(4),
    --             ["<C-Space>"] = cmp.mapping.complete(),
    --             ["<C-e>"] = cmp.mapping.abort(),
    --             ["<CR>"] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
    --         }),
    --     })
    --
    --     -- Use cmdline & path source for ':' (if you enabled `native_menu`, this won't work anymore).
    --     cmp.setup.cmdline(":", {
    --         mapping = cmp.mapping.preset.cmdline(),
    --         sources = cmp.config.sources({
    --             { name = "path" },
    --         }, {
    --             { name = "cmdline" },
    --         }),
    --     })
    --
    --     require("luasnip.loaders.from_vscode").lazy_load()
    -- end,
}
